### ISSUE TITLE
Malformed Search/Get Request Causes "thread 'main' panicked at 'not yet implemented', src/main.rs:109:21"

### ISSUE THREAD

**Issue by tuxruffian** [MinisculeGirraffe/tdl#33]
This happens with both the downloaded release and if I clone the repo and build it manually.  I can access help and login which works and creates the config file, but any `search` or `get` command triggers the panic.  Full backtrace below:

```
tdl search any                                                                             17:33:29 [2/599]
Access Token Valid
thread 'main' panicked at 'not yet implemented', src/main.rs:109:21
stack backtrace:
   0:      0x326fee9ae71 - <unknown>
   1:      0x326fec109dc - <unknown>
   2:      0x326fee770e4 - <unknown>
   3:      0x326fee9bf96 - <unknown>
   4:      0x326fee9d007 - <unknown>
   5:      0x326fee9cabb - <unknown>
   6:      0x326fee9ca56 - <unknown>
   7:      0x326fee9ca12 - <unknown>
   8:      0x326fead5ed2 - <unknown>
   9:      0x326fead5fcc - <unknown>
  10:      0x326feb30137 - <unknown>
  11:      0x326feb23332 - <unknown>
  12:      0x326fef31f3c - <unknown>
  13:      0x326fef14e23 - <unknown>
  14:      0x326fef302e6 - <unknown>
  15:     0x6efbead58cd0 - <unknown>
  16:     0x6efbead58d8a - __libc_start_main
  17:      0x326feaf48ee - <unknown>
  18:                0x0 - <unknown>
```
Linked output:

```
ldd tdl
        linux-vdso.so.1 (0x00006125ff07a000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00006125fefbf000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00006125fe400000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00006125fef9a000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00006125fef95000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00006125fe713000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00006125fef90000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00006125fe21e000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00006125ff07c000)
```

**Comment by tuxruffian** [comment]
It appears that the panic is only triggered by a malformed request.  Not a great error....but it does work when there are no errors in the request.  I will keep the issue open in case others come across it and think it's not functioning when it is just an unhandled error.
